my_file2=open("people3.txt","w")
my_file2.write("Abhishek-Gurgaon")
my_file2.write("Ranveer-Delhi")
print ("AbhishekRanveer")
print ("---------------------------------")
print ("Abhishek\nRanveer")
print ("---------------------------------")
print ("Abhishek\n\nRanveer")
print ("---------------------------------") 
my_file2.close()